-- V1__Baseline_Schema.sql
-- Create initial schema definitions for core entities

-- 1. room table
CREATE TABLE room (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    location VARCHAR(255),
    width_m REAL NOT NULL,
    length_m REAL NOT NULL,
    floor_plan_image VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE
);

-- 2. rack table
CREATE TABLE rack (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id BIGINT NOT NULL REFERENCES room(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    total_units INTEGER NOT NULL,
    pos_x REAL NOT NULL,
    pos_y REAL NOT NULL,
    rotation_deg REAL,
    length REAL NOT NULL DEFAULT 1.0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE
);

-- 3. device_type table
CREATE TABLE device_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(50) NOT NULL,
    height_u INTEGER NOT NULL,
    width_mm REAL,
    length_mm REAL,
    weight_kg REAL,
    image_path VARCHAR(255),
    front_image_path VARCHAR(255),
    rear_image_path VARCHAR(255),
    oid_uptime VARCHAR(255),
    oid_cpu VARCHAR(255),
    oid_ram VARCHAR(255),
    oid_network VARCHAR(255),
    oid_temp VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- 4. module_type table
CREATE TABLE module_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manufacturer VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    part_number VARCHAR(255)
);

-- 5. device table
CREATE TABLE device (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rack_id BIGINT NOT NULL REFERENCES rack(id) ON DELETE CASCADE,
    device_type_id BIGINT NOT NULL REFERENCES device_type(id),
    name VARCHAR(255),
    start_u INTEGER NOT NULL,
    face VARCHAR(20) NOT NULL DEFAULT 'FRONT',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    ip_address VARCHAR(255),
    port INTEGER,
    snmp_community VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE
);

-- 6. device_module table
CREATE TABLE device_module (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL REFERENCES device(id) ON DELETE CASCADE,
    module_type_id BIGINT NOT NULL REFERENCES module_type(id),
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE'
);

-- 7. device_module_bay table
CREATE TABLE device_module_bay (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    label VARCHAR(255),
    position VARCHAR(255),
    device_id BIGINT NOT NULL REFERENCES device(id) ON DELETE CASCADE,
    installed_module_id BIGINT REFERENCES device_module(id) ON DELETE SET NULL
);

-- 8. device_console_port table
CREATE TABLE device_console_port (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255),
    device_id BIGINT NOT NULL REFERENCES device(id) ON DELETE CASCADE,
    module_id BIGINT REFERENCES device_module(id) ON DELETE CASCADE
);

-- 9. device_power_port table
CREATE TABLE device_power_port (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255),
    device_id BIGINT NOT NULL REFERENCES device(id) ON DELETE CASCADE,
    module_id BIGINT REFERENCES device_module(id) ON DELETE CASCADE
);

-- 10. device_interface table
CREATE TABLE device_interface (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    mac_address VARCHAR(255),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    device_id BIGINT NOT NULL REFERENCES device(id) ON DELETE CASCADE,
    module_id BIGINT REFERENCES device_module(id) ON DELETE CASCADE
);

-- 11. pdu table
CREATE TABLE pdu (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rack_id BIGINT NOT NULL REFERENCES rack(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    position VARCHAR(20) NOT NULL,
    outlet_count INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- 12. console_port_template table
CREATE TABLE console_port_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255),
    device_type_id BIGINT REFERENCES device_type(id) ON DELETE CASCADE,
    module_type_id BIGINT REFERENCES module_type(id) ON DELETE CASCADE
);

-- 13. power_port_template table
CREATE TABLE power_port_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255),
    device_type_id BIGINT REFERENCES device_type(id) ON DELETE CASCADE,
    module_type_id BIGINT REFERENCES module_type(id) ON DELETE CASCADE
);

-- 14. interface_template table
CREATE TABLE interface_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    mgmt_only BOOLEAN NOT NULL DEFAULT FALSE,
    device_type_id BIGINT REFERENCES device_type(id) ON DELETE CASCADE,
    module_type_id BIGINT REFERENCES module_type(id) ON DELETE CASCADE
);

-- 15. module_bay_template table
CREATE TABLE module_bay_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    label VARCHAR(255),
    position VARCHAR(255),
    device_type_id BIGINT NOT NULL REFERENCES device_type(id) ON DELETE CASCADE
);

-- 16. equipment_alarms table
CREATE TABLE equipment_alarms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL,
    metric_key VARCHAR(50) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    message VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    acknowledged_at TIMESTAMP WITH TIME ZONE,
    acknowledged_by VARCHAR(255),
    note VARCHAR(255),
    resolved_at TIMESTAMP WITH TIME ZONE
);

-- GIN trigram indexes for device name & ip_address search
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX idx_device_name_trgm ON device USING gin (name gin_trgm_ops);
CREATE INDEX idx_device_ip_trgm ON device USING gin (ip_address gin_trgm_ops);
